config:
  backend_uri: "backend.minikube.local"
image:
  repository: rkundani/frontend
  tag: "1.0"
replicaCount: 1
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  host: frontend.minikube.local
autoScaling:
  minReplicas: 1
  maxReplicas: 10
